package com.mnhmilu.poc.localstack.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.ToString;

import static com.mnhmilu.poc.localstack.common.DynamoDBIndexes.*;

@DynamoDBTable(tableName = "subscription")
@ToString
public class SubscriptionEntity {

    private String walletNo;

    private String externalRequestId;

    private String status;

    private String accountNo;

    private String subscriptionRequestId;

    //private ProductEntity product;

    @DynamoDBHashKey
    public String getWalletNo() {
        return walletNo;
    }

    public void setWalletNo(String walletNo) {
        this.walletNo = walletNo;
    }

    @DynamoDBIndexRangeKey(localSecondaryIndexName = INDEX_ACCOUNT_NO)
    public String getAccountNo() {
        return accountNo;
    }

    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo;
    }

    @DynamoDBRangeKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBIndexHashKey(globalSecondaryIndexName = INDEX_EXTERNAL_REQUEST_ID)
    public String getExternalRequestId() {
        return externalRequestId;
    }

    public void setExternalRequestId(String externalRequestId) {
        this.externalRequestId = externalRequestId;
    }

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = INDEX_SUBSCRIPTION_REQUEST_ID)
    public String getSubscriptionRequestId() {
        return subscriptionRequestId;
    }

    public void setSubscriptionRequestId(String subscriptionRequestId) {
        this.subscriptionRequestId = subscriptionRequestId;
    }

    @DynamoDBAttribute(attributeName = "status")
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

}